### ISSUE TITLE
What's this? 

### ISSUE THREAD

**Issue by chucknezi** [sal-git/RecruitieProject#1]

**Comment by sal-git** [comment]
@chucknezi I want to create an open source project for recruiters. I don't know if they use any software that keeps track of all the jobs, their candidates, automate email sending if there is skill match, and etc. And I kinda want to showcase my skills in a recent project 😅

Pull and push if you want. 👍

**Comment by chucknezi** [comment]
@sal-git That's dope! Busy at the moment, but I'll definitely check it out when I get a chance.
